const cases={
anonymous:{
tag:'HACKTIVISM / CASE_001',
title:'ANONYMOUS // VERIFIED CASE FILE',
html:`
<div class="casehero"><div><div class="tag">HACKTIVISM / CASE_001 / EVIDENCE-BASED</div><h2>WHO ARE<br>ANONYMOUS?</h2><p class="lede">Not a conventional organization, but a decentralized identity used by changing groups of online participants. This file separates documented events from claims and folklore.</p></div><div class="case-meta"><b>FILE STATUS</b><span>OPEN</span><b>PUBLIC EMERGENCE</b><span>2000s / major activist turn in 2008</span><b>STRUCTURE</b><span>Decentralized / no verified central command</span><b>CONFIDENCE</b><span>High on listed historical events; attribution varies by operation</span></div></div>
<div class="warning">NODE404 NOTE // “Anonymous” is a shared label. A claim made under the name does not by itself prove who performed an action. This archive attributes only what credible reporting, court records, or primary documentation supports.</div>
<h4>01 // ORIGIN OF THE IDENTITY</h4>
<p>The identity grew out of anonymous imageboard culture, especially 4chan, where users posting without names appeared as “Anonymous.” Early activity was often trolling and online pranks rather than a coherent political program. Reporting on the movement describes a deliberately leaderless culture in which the same collective identity could be used by many unrelated participants.</p>
<div class="evidence"><b>DOCUMENTED</b><span>The collective identity and leaderless culture predate its best-known political campaigns.</span></div>
<h4>02 // PROJECT CHANOLOGY — 2008</h4>
<p>Anonymous became internationally visible in January 2008 during <b>Project Chanology</b>, a campaign against the Church of Scientology after attempts to suppress a leaked Tom Cruise Scientology video. Early actions included online disruption and DDoS attacks. The campaign then moved into physical protests. On February 10, 2008, thousands of protesters appeared in cities around the world, many wearing Guy Fawkes masks. That period helped turn the mask into the movement’s best-known visual symbol.</p>
<div class="timeline"><div><time>JAN 2008</time><strong>PROJECT CHANOLOGY</strong><span>Online campaign against Scientology begins.</span></div><div><time>FEB 10 2008</time><strong>GLOBAL STREET PROTESTS</strong><span>Anonymous participants demonstrate outside Scientology facilities in more than 90 cities, according to contemporary reporting.</span></div></div>
<h4>03 // WIKILEAKS & OPERATION PAYBACK — 2010</h4>
<p>In late 2010, Anonymous-associated participants carried out DDoS attacks against companies seen as acting against WikiLeaks. U.S. court records document attacks on PayPal after it suspended WikiLeaks’ donation account. The Justice Department later said defendants admitted participating in the December 2010 PayPal DDoS attack, referred to as <b>Operation Avenge Assange</b>. Contemporary reporting also documented Anonymous-associated DDoS attacks against MasterCard and Visa.</p>
<div class="statrow"><div><small>DEC 2010</small><b>PAYPAL</b><span>DDoS attack documented in U.S. federal cases</span></div><div><small>2011</small><b>14 ARRESTS</b><span>U.S. arrests tied to alleged PayPal attack roles</span></div><div><small>2013</small><b>13 GUILTY PLEAS</b><span>Federal pleas related to the PayPal attack</span></div></div>
<h4>04 // HBGARY FEDERAL — 2011</h4>
<p>HBGary Federal CEO Aaron Barr publicly indicated that he had identified people he believed were central Anonymous figures. Anonymous-associated attackers then compromised HBGary Federal. Contemporary technical reporting documented a chain of security failures, including a vulnerable web application, weak/reused passwords and later access to company systems and email. More than 40,000 emails were reported stolen and published, and backup data was deleted. Barr’s attempt to map Anonymous identities was also reported to contain serious errors.</p>
<div class="evidence"><b>WHY IT MATTERS</b><span>The incident became one of the clearest documented examples of an operation carried out under the Anonymous banner producing major real-world consequences for a security company.</span></div>
<h4>05 // LAW ENFORCEMENT RESPONSE</h4>
<p>The idea that Anonymous participants were completely untraceable is false. In July 2011, the U.S. Department of Justice announced 14 arrests tied to the alleged PayPal DDoS attack, alongside other cyber arrests. In December 2013, DOJ announced that 13 defendants had pleaded guilty to charges connected to the December 2010 PayPal attack. The prosecutions demonstrate an important distinction: a decentralized collective identity can be difficult to define, while individual participants can still be identified and prosecuted.</p>
<h4>06 // WHAT ANONYMOUS ACTUALLY IS</h4>
<div class="truthgrid"><div><b>NO VERIFIED CENTRAL LEADER</b><p>Anonymous has historically operated as a decentralized identity rather than a conventional membership organization.</p></div><div><b>NO SINGLE IDEOLOGY</b><p>Different operations have involved different participants, goals and tactics. Statements made under the name can conflict.</p></div><div><b>THE MASK IS A SYMBOL</b><p>The Guy Fawkes mask became strongly associated with Anonymous during the 2008 Scientology protests.</p></div><div><b>ATTRIBUTION IS HARD</b><p>Anyone can claim the label. Responsible reporting must distinguish a public claim from independently verified responsibility.</p></div></div>
<h4>07 // VERIFIED TIMELINE</h4>
<div class="big-timeline"><div><time>2000s</time><p><b>Anonymous identity develops</b><br>Anonymous imageboard culture produces the shared “Anonymous” identity.</p></div><div><time>2008</time><p><b>Project Chanology</b><br>Campaign against Scientology moves from online disruption to international street protests.</p></div><div><time>2010</time><p><b>Operation Payback / WikiLeaks-related actions</b><br>DDoS actions target financial services including PayPal; MasterCard and Visa are also reported targets.</p></div><div><time>2011</time><p><b>HBGary Federal compromise</b><br>Company systems and email are compromised after CEO Aaron Barr’s effort to identify Anonymous participants.</p></div><div><time>2011</time><p><b>Federal arrests</b><br>DOJ announces arrests tied to the PayPal attack investigation.</p></div><div><time>2013</time><p><b>Guilty pleas</b><br>Thirteen defendants plead guilty in federal court to charges related to the PayPal DDoS attack.</p></div></div>
<h4>08 // WHAT WE WILL NOT PRESENT AS FACT</h4>
<ul class="redflags"><li>That every operation announced as “Anonymous” came from the same people.</li><li>That Anonymous has one secret global leader or a verified permanent membership list.</li><li>That a social-media account using Anonymous branding automatically represents the wider movement.</li><li>Unverified claims of hacks, leaks or identities without independent evidence.</li></ul>
<h4>09 // SOURCES & EVIDENCE</h4>
<div class="sources"><a target="_blank" href="https://www.wired.com/2009/09/mf-chanology/"><b>WIRED — Project Chanology</b><span>Detailed contemporary history of the 2008 Scientology campaign and protests.</span></a><a target="_blank" href="https://www.wired.com/2012/07/ff-anonymous/"><b>WIRED — How Anonymous Picks Targets</b><span>Long-form reporting on Anonymous culture, Chanology and DDoS activism.</span></a><a target="_blank" href="https://www.justice.gov/usao-ndca/pr/thirteen-defendants-plead-guilty-december-2010-cyber-attack-against-paypal"><b>U.S. DOJ — 13 Guilty Pleas</b><span>Primary federal record concerning the December 2010 PayPal DDoS attack.</span></a><a target="_blank" href="https://www.justice.gov/archives/opa/pr/sixteen-individuals-arrested-united-states-alleged-roles-cyber-attacks"><b>U.S. DOJ — 2011 Arrests</b><span>Primary federal record of arrests related to the PayPal investigation.</span></a><a target="_blank" href="https://arstechnica.com/tech-policy/2011/02/anonymous-speaks-the-inside-story-of-the-hbgary-hack/"><b>ARS TECHNICA — HBGary Investigation</b><span>Technical reconstruction of the HBGary Federal compromise.</span></a><a target="_blank" href="https://www.theguardian.com/technology/2011/may/11/anonymous-behind-the-mask"><b>THE GUARDIAN — Behind the Mask</b><span>Background on Anonymous identity, leaderlessness and symbolism.</span></a></div>
<div class="endfile">END OF PUBLIC FILE // CASE_001<br><span>VERIFY EVERYTHING. ATTRIBUTE CAREFULLY. DISTINGUISH FACT FROM CLAIM.</span></div>`},
cicada:{tag:'INTERNET MYSTERY / CASE_002',title:'CICADA 3301',html:'<p>Case file queued for evidence review.</p>'},
wannacry:{tag:'CYBER HISTORY / CASE_003',title:'WANNACRY',html:'<p>Case file queued for evidence review.</p>'}}
function openCase(id){const c=cases[id];document.getElementById('modalContent').innerHTML=c.html?c.html:`<div class="tag">${c.tag}</div><h2>${c.title}</h2>`;document.getElementById('modal').classList.add('on');document.querySelector('.modal').scrollTop=0}
function closeCase(){document.getElementById('modal').classList.remove('on')}
function randomCase(){openCase(Object.keys(cases)[Math.floor(Math.random()*3)])}
function searchArchive(){let q=document.getElementById('search').value.toLowerCase();let id=Object.keys(cases).find(k=>k.includes(q)||cases[k].title.toLowerCase().includes(q));if(id)openCase(id);else alert('NO MATCHING RECORD FOUND // TRY: anonymous, cicada, wannacry')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCase()});
